### ISSUE TITLE
Invalid Link on https://www.astrouxds.com/getting-started/designers/

### ISSUE THREAD

**Issue by umich-mel** [RocketCommunicationsInc/astro-www#370]
When clicking on the link for [Astro Storybook] in the line:

Before reading any further, we recommend you review available Astro components on the [Astro Storybook](https://astro-components.netlify.app/?path=/story/astro-uxds-welcome-start-here--page&_gl=1*1o1ogep*_ga*ODE5MDc1NTc0LjE3MTE1NTI5OTg.*_ga_ZHMMGPG3B3*MTcxMTU1Mjk5Ny4xLjEuMTcxMTU1MzE2Ny4wLjAuMA..) site.

The new page that opens has the message: 

Couldn't find story matching 'astro-uxds-welcome-start-here--page'.
- Are you sure a story with that id exists?
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.

**Comment by kiley-mitti** [comment]
Hey @umich-mel, Thanks for the heads up. We've fixed this link on https://www.astrouxds.com/getting-started/designers/ so that it directs to the Storybook Welcome page as intended. If you notice any other issues please don't hesitate to reach out!

**Comment by umich-mel** [comment]
Awesome, looks good. My first time reporting an issue, so glad I could help 😊

From: Kiley ***@***.***>
Sent: Wednesday, March 27, 2024 9:18 AM
To: RocketCommunicationsInc/astro-www ***@***.***>
Cc: Lash, Michael E [US] (SP) ***@***.***>; Mention ***@***.***>
Subject: EXT :Re: [RocketCommunicationsInc/astro-www] Invalid Link on https://www.astrouxds.com/getting-started/designers/ (Issue #370)


Hey @umich-mel<https://github.com/umich-mel>, Thanks for the heads up. We've fixed this link on https://www.astrouxds.com/getting-started/designers/ so that it directs to the Storybook Welcome page as intended. If you notice any other issues please don't hesitate to reach out!
